from .reflection import REFLECTION_PROMPT
from .swarm import (
    SWARM_PROMPT_TREND, 
    SWARM_PROMPT_REVERSION, 
    SWARM_PROMPT_SCALPER, 
    MASTER_AGGREGATION_PROMPT
)
from .risk import RISK_MANAGER_PROMPT
from .simple import SIMPLE_TRADING_PROMPT
