
"""
Risk Assessment Agent Module.

This module implements the "Risk Officer" agent.
It uses an LLM to evaluate trade setups generated by the Swarm.
Its goal is to Protect Capital and Beat BTC Buy & Hold by:
1.  Assigning dynamic leverage (5x default, 10x for A+ setups).
2.  Calculating dynamic position sizing based on conviction (Risk %).
3.  Defining technical invalidation levels (Stop Loss).

It outputs a structured JSON decision that overrides default sizing logic.
"""
import os
import json
import logging
from typing import Dict, Any, Optional

from openai import AsyncOpenAI
from dotenv import load_dotenv

# Project Imports
from prompt import RISK_MANAGER_PROMPT
from core.risk_engine import risk_engine

# Configure logging
logging.basicConfig(level=logging.INFO)
logger = logging.getLogger(__name__)

load_dotenv()

class RiskAssessmentAgent:
    """
    The Risk Officer.
    
    Attributes:
        client (AsyncOpenAI): LLM client.
    """
    def __init__(self):
        api_key = os.getenv("OPENROUTER_API_KEY")
        self.client = AsyncOpenAI(
             base_url="https://openrouter.ai/api/v1",
             api_key=api_key
        )
        self.model = "google/gemini-2.0-flash-001" # Fast, smart model for Risk

    async def assess_risk(
        self, 
        signal: str, 
        symbol: str, 
        current_price: float, 
        swarm_reasoning: str,
        swarm_confidence: float,
        market_data: Dict[str, Any],
        account_equity: float,
        current_positions: Dict[str, Any] = {}
    ) -> Dict[str, Any]:
        """
        Evaluate the trade risk and determine sizing/leverage/SL using Institutional Math + LLM.
        """
        # 1. Extract Technicals (ATR for Volatility)
        atr_1h = 0.0
        try:
            # Try to grab 4h, then 1h, then 15m ATR
            if market_data.get("4h", {}).get("atr14"):
                atr_1h = market_data.get("4h", {}).get("atr14", [])[-1]
                period = "4h"
            elif market_data.get("1h", {}).get("atr14"):
                atr_1h = market_data.get("1h", {}).get("atr14", [])[-1]
                period = "1h"
            else:
                atr_1h = 0.0
                period = "1d"
            
            recent_data = {
                "current_price": current_price,
                "atr_val": atr_1h,
                "atr_period": period,
                "rsi_4h": market_data.get("4h", {}).get("rsi14", [])[-1] if market_data.get("4h", {}).get("rsi14") else "N/A",
                "trend_4h": "BULLISH" if (market_data.get("4h", {}).get("midPrices", [0])[-1] > market_data.get("4h", {}).get("ema50", [0])[-1]) else "BEARISH"
            }
        except Exception as e:
            logger.warning(f"Error extracting context for Risk Agent: {e}")
            recent_data = {"error": "Could not extract deep technicals"}

        # 2. QUANTITATIVE SIZING (The Math Layer)
        # A. Volatility Targeting
        raw_vol_size = risk_engine.calculate_vol_target_size(
            account_equity=account_equity,
            current_price=current_price,
            atr_value=float(atr_1h) if atr_1h else 0.0,
            atr_period=recent_data.get("atr_period", "1d")
        )
        
        # B. Correlation Check
        final_quant_size = risk_engine.apply_correlation_penalty(
            account_equity=account_equity,
            new_symbol=symbol,
            proposed_size_usd=raw_vol_size,
            current_positions=current_positions
        )
        
        quant_msg = (
            f"Based on {risk_engine.TARGET_VOL*100}% Annual Vol Target and ATR ({atr_1h:.2f}), "
            f"Max Size is ${raw_vol_size:.2f}. "
            f"After Correlation Penalty (Portfolio Heat), Safe Cap is: ${final_quant_size:.2f}."
        )

        # 3. Construct Prompt
        prompt = RISK_MANAGER_PROMPT.format(
            symbol=symbol,
            signal=signal,
            current_price=current_price,
            swarm_confidence=swarm_confidence,
            swarm_reasoning=swarm_reasoning,
            equity=account_equity,
            technical_context=json.dumps(recent_data, indent=2),
            quant_guidance=quant_msg
        )

        try:
            logger.info(f"Risk Agent evaluating {symbol} ({signal}). Quant Cap: ${final_quant_size:.2f}")
            completion = await self.client.chat.completions.create(
                model=self.model,
                messages=[
                    {"role": "system", "content": "You are the Senior Risk Officer. TRUST THE MATH. Do not exceed Quant Caps without extraordinary justification."},
                    {"role": "user", "content": prompt}
                ],
                temperature=0.2, # Low temp for deterministic math/logic
                response_format={ "type": "json_object" }
            )
            
            response_text = completion.choices[0].message.content
            decision = json.loads(response_text)
            
            # Post-Processing / Guardrails
            # Hard Cap at Quant Size if Agent tries to go rogue?
            # For now, let's respect the agent but log warning if it exceeds
            if decision.get("position_size_usd", 0) > final_quant_size * 1.1: # 10% tolerance
                logger.warning(f"Risk Agent exceeded Quant Cap! Cap: {final_quant_size}, Agent: {decision['position_size_usd']}")
                # Force Cap? User said "Risk Engine Upgrade". Let's ENABLE HARD CAP.
                decision["position_size_usd"] = min(decision["position_size_usd"], final_quant_size)
                decision["reasoning"] += f" [CAPPED BY QUANT RISK ENGINE at ${final_quant_size:.2f}]"

            decision["leverage"] = max(1, min(decision.get("leverage", 5), 10))
            
            return decision

        except Exception as e:
            logger.error(f"Risk Agent failed: {e}")
            # Fallback to safe defaults
            return {
                "signal": "REJECTED",
                "reasoning": f"Risk Agent Error: {e}",
                "leverage": 1,
                "size_usd": 0.0
            }
